-- MySQL Script generated by MySQL Workbench
-- Thu Sep 15 13:31:07 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`ideologys`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ideologys` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `discription` VARCHAR(45) NOT NULL,
  `skills` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`religions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`religions` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `discription` VARCHAR(45) NOT NULL,
  `skills` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fractions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fractions` (
  `id` INT NOT NULL,
  `ideologys_id` INT NOT NULL,
  `religions_id` INT NOT NULL,
  `player_nick` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `discription` VARCHAR(45) NOT NULL,
  `lord` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `ideologys_id`, `religions_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`resources`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`resources` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`military`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`military` (
  `id` INT NOT NULL,
  `size` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`moves`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`moves` (
  `id` INT NOT NULL,
  `size` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`divisions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`divisions` (
  `id` INT NOT NULL,
  `moves_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `discription` VARCHAR(45) NOT NULL,
  `defensive` VARCHAR(45) NOT NULL,
  `attack` VARCHAR(45) NOT NULL,
  `health` VARCHAR(45) NOT NULL,
  `skills` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `moves_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`maps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`maps` (
  `id` INT NOT NULL,
  `resources_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `discription` VARCHAR(45) NOT NULL,
  `size` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `resources_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`biomes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`biomes` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `discription` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`buildings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`buildings` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `discription` VARCHAR(45) NOT NULL,
  `special` VARCHAR(45) NULL,
  `skill` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`maps_has_biomes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`maps_has_biomes` (
  `maps_id` INT NOT NULL,
  `biomes_id` INT NOT NULL,
  PRIMARY KEY (`maps_id`, `biomes_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`biomes_has_resources`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`biomes_has_resources` (
  `biomes_id` INT NOT NULL,
  `resources_id` INT NOT NULL,
  `size` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`biomes_id`, `resources_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`buildings_has_resources`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`buildings_has_resources` (
  `buildings_id` INT NOT NULL,
  `resources_id` INT NOT NULL,
  `size` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`buildings_id`, `resources_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`military_has_divisions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`military_has_divisions` (
  `military_id` INT NOT NULL,
  `divisions_id` INT NOT NULL,
  `divisions_moves_id` INT NOT NULL,
  `special` VARCHAR(45) NULL,
  PRIMARY KEY (`military_id`, `divisions_id`, `divisions_moves_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`divisions_has_resources`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`divisions_has_resources` (
  `divisions_id` INT NOT NULL,
  `divisions_moves_id` INT NOT NULL,
  `resources_id` INT NOT NULL,
  `size` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`divisions_id`, `divisions_moves_id`, `resources_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`maps_has_buildings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`maps_has_buildings` (
  `maps_id` INT NOT NULL,
  `maps_resources_id` INT NOT NULL,
  `buildings_id` INT NOT NULL,
  PRIMARY KEY (`maps_id`, `maps_resources_id`, `buildings_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`maps_has_fractions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`maps_has_fractions` (
  `maps_id` INT NOT NULL,
  `maps_resources_id` INT NOT NULL,
  `fractions_id` INT NOT NULL,
  `fractions_ideologys_id` INT NOT NULL,
  `fractions_religions_id` INT NOT NULL,
  PRIMARY KEY (`maps_id`, `maps_resources_id`, `fractions_id`, `fractions_ideologys_id`, `fractions_religions_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fractions_has_military`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fractions_has_military` (
  `fractions_id` INT NOT NULL,
  `fractions_ideologys_id` INT NOT NULL,
  `fractions_religions_id` INT NOT NULL,
  `military_id` INT NOT NULL,
  PRIMARY KEY (`fractions_id`, `fractions_ideologys_id`, `fractions_religions_id`, `military_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
